version: '3'
services:
  hello-dropwizard:
    image: hello-dropwizard
    ports:
      - 8080
    restart: always
    deploy:
     replicas: 5
     update_config:
       parallelism: 2
       delay: 10s
     restart_policy:
       condition: on-failure
       max_attempts: 3
       window: 120s
    networks:
      - web

  nginx:
    image: nginx:stable
    restart: always
    depends_on:
      - hello-dropwizard
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
    networks:
      - web
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  web:
    driver: overlay